# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
# REPO_NAME could be any repository name
#I use secret to define my repo name
env:
  REPO_NAME: ${{ secrets.REPO_NAME }}
  File_To_Change: configTest.json

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
#       - uses: actions/checkout@v2
          
      - name: Checkout tools repo ${{ env.REPO_NAME }}
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.TOKEN }}
          repository: ${{ env.REPO_NAME }}
          ref: master
#          path: /home/runner/work/test-repo-I
          
      - name: Run a multi-line script
        run: |
          tree /home/
          cat /home/runner/work/${{ github.event.repository.name }}/${{ github.event.repository.name }}/${{ env.File_To_Change }}
#          shell: bash

      - name: Update ${{ env.File_To_Change }} description
        uses: jossef/action-set-json-field@v1
        with:
          file: /home/runner/work/${{ github.event.repository.name }}/${{ github.event.repository.name }}/${{ env.File_To_Change }}
          field: github.description
          value: New Secrets
          
      - name: Cat ${{ env.File_To_Change }} after changes
        run: cat /home/runner/work/${{ github.event.repository.name }}/${{ github.event.repository.name }}/${{ env.File_To_Change }}
          
      - name: Commit files
        run: |
          git config --local user.email "${{ secrets.USER_EMAIL }}"
          git config --local user.name "${{ secrets.USER_NAME }}"
          git commit -m "Add changes" -a
          git push https://github.com/${{ env.REPO_NAME }}.git master
          
#       - name: Push changes
#         uses: ad-m/github-push-action@master
#         with:
#           github_token: ${{ secrets.TOKEN }}
#           repository: ${{ env.REPO_NAME }}
#           branch: master
